spring.application.name=forum-service
server.port=8082
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8888/eureka/

spring.datasource.url=jdbc:h2:mem:ForumServiceDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=master
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
