server.port=8888
spring.application.name=server
eureka.client.service-url.defaultZone=http://localhost:8888/eureka/
spring.cloud.config.server.git.uri=https://github.com/ViniciusHC/boardgame-config-repo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false