spring.application.name=ApiGatewayBG
spring.config.import=optional:configserver:http://localhost:8888
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8888/eureka/
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=gateway
